# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/assignCOG.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssignCOGsDlg(object):
    def setupUi(self, AssignCOGsDlg):
        AssignCOGsDlg.setObjectName("AssignCOGsDlg")
        AssignCOGsDlg.resize(357, 102)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/appendCOGs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AssignCOGsDlg.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(AssignCOGsDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtInputProfile = QtWidgets.QLineEdit(AssignCOGsDlg)
        self.txtInputProfile.setReadOnly(True)
        self.txtInputProfile.setObjectName("txtInputProfile")
        self.horizontalLayout.addWidget(self.txtInputProfile)
        self.btnLoadProfiles = QtWidgets.QPushButton(AssignCOGsDlg)
        self.btnLoadProfiles.setObjectName("btnLoadProfiles")
        self.horizontalLayout.addWidget(self.btnLoadProfiles)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(AssignCOGsDlg)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.cboMultiCogTreatment = QtWidgets.QComboBox(AssignCOGsDlg)
        self.cboMultiCogTreatment.setObjectName("cboMultiCogTreatment")
        self.cboMultiCogTreatment.addItem("")
        self.cboMultiCogTreatment.addItem("")
        self.horizontalLayout_3.addWidget(self.cboMultiCogTreatment)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnCreateProfile = QtWidgets.QPushButton(AssignCOGsDlg)
        self.btnCreateProfile.setEnabled(False)
        self.btnCreateProfile.setObjectName("btnCreateProfile")
        self.horizontalLayout_2.addWidget(self.btnCreateProfile)
        self.btnCancel = QtWidgets.QPushButton(AssignCOGsDlg)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(AssignCOGsDlg)
        QtCore.QMetaObject.connectSlotsByName(AssignCOGsDlg)

    def retranslateUi(self, AssignCOGsDlg):
        _translate = QtCore.QCoreApplication.translate
        AssignCOGsDlg.setWindowTitle(_translate("AssignCOGsDlg", "Assign COG categories"))
        self.btnLoadProfiles.setText(_translate("AssignCOGsDlg", "Load profiles"))
        self.label.setText(_translate("AssignCOGsDlg", "Multi-code COG treatment:"))
        self.cboMultiCogTreatment.setItemText(0, _translate("AssignCOGsDlg", "Assign sequence to each COG code"))
        self.cboMultiCogTreatment.setItemText(1, _translate("AssignCOGsDlg", "Treat multi-code COGs as features"))
        self.btnCreateProfile.setText(_translate("AssignCOGsDlg", "Create STAMP profile"))
        self.btnCancel.setText(_translate("AssignCOGsDlg", "Cancel"))
from stamp import STAMP_rc
