# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/createProfileRITA.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProfileRITADlg(object):
    def setupUi(self, CreateProfileRITADlg):
        CreateProfileRITADlg.setObjectName("CreateProfileRITADlg")
        CreateProfileRITADlg.resize(595, 295)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stamp/GUI/../icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateProfileRITADlg.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CreateProfileRITADlg)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnLoadProfiles = QtWidgets.QPushButton(CreateProfileRITADlg)
        self.btnLoadProfiles.setObjectName("btnLoadProfiles")
        self.verticalLayout.addWidget(self.btnLoadProfiles)
        self.groupBox = QtWidgets.QGroupBox(CreateProfileRITADlg)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chkNB_DBLASTN = QtWidgets.QCheckBox(self.groupBox)
        self.chkNB_DBLASTN.setChecked(True)
        self.chkNB_DBLASTN.setObjectName("chkNB_DBLASTN")
        self.verticalLayout_2.addWidget(self.chkNB_DBLASTN)
        self.chkDBLASTN = QtWidgets.QCheckBox(self.groupBox)
        self.chkDBLASTN.setChecked(True)
        self.chkDBLASTN.setObjectName("chkDBLASTN")
        self.verticalLayout_2.addWidget(self.chkDBLASTN)
        self.chkNB_BLASTN = QtWidgets.QCheckBox(self.groupBox)
        self.chkNB_BLASTN.setChecked(True)
        self.chkNB_BLASTN.setObjectName("chkNB_BLASTN")
        self.verticalLayout_2.addWidget(self.chkNB_BLASTN)
        self.chkBLASTN = QtWidgets.QCheckBox(self.groupBox)
        self.chkBLASTN.setChecked(True)
        self.chkBLASTN.setObjectName("chkBLASTN")
        self.verticalLayout_2.addWidget(self.chkBLASTN)
        self.chkNB_BLASTX = QtWidgets.QCheckBox(self.groupBox)
        self.chkNB_BLASTX.setChecked(True)
        self.chkNB_BLASTX.setObjectName("chkNB_BLASTX")
        self.verticalLayout_2.addWidget(self.chkNB_BLASTX)
        self.chkBLASTX = QtWidgets.QCheckBox(self.groupBox)
        self.chkBLASTX.setChecked(True)
        self.chkBLASTX.setObjectName("chkBLASTX")
        self.verticalLayout_2.addWidget(self.chkBLASTX)
        self.chkNB = QtWidgets.QCheckBox(self.groupBox)
        self.chkNB.setChecked(True)
        self.chkNB.setObjectName("chkNB")
        self.verticalLayout_2.addWidget(self.chkNB)
        self.verticalLayout.addWidget(self.groupBox)
        self.btnCreateProfile = QtWidgets.QPushButton(CreateProfileRITADlg)
        self.btnCreateProfile.setEnabled(False)
        self.btnCreateProfile.setObjectName("btnCreateProfile")
        self.verticalLayout.addWidget(self.btnCreateProfile)
        self.btnCancel = QtWidgets.QPushButton(CreateProfileRITADlg)
        self.btnCancel.setObjectName("btnCancel")
        self.verticalLayout.addWidget(self.btnCancel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.lstSelectedProfiles = QtWidgets.QListWidget(CreateProfileRITADlg)
        self.lstSelectedProfiles.setObjectName("lstSelectedProfiles")
        self.horizontalLayout.addWidget(self.lstSelectedProfiles)

        self.retranslateUi(CreateProfileRITADlg)
        QtCore.QMetaObject.connectSlotsByName(CreateProfileRITADlg)

    def retranslateUi(self, CreateProfileRITADlg):
        _translate = QtCore.QCoreApplication.translate
        CreateProfileRITADlg.setWindowTitle(_translate("CreateProfileRITADlg", "Create profile"))
        self.btnLoadProfiles.setText(_translate("CreateProfileRITADlg", "Load profiles"))
        self.groupBox.setTitle(_translate("CreateProfileRITADlg", "Groups to retain"))
        self.chkNB_DBLASTN.setText(_translate("CreateProfileRITADlg", "NB and D-BLASTN"))
        self.chkDBLASTN.setText(_translate("CreateProfileRITADlg", "D-BLASTN ratio"))
        self.chkNB_BLASTN.setText(_translate("CreateProfileRITADlg", "NB and BLASTN"))
        self.chkBLASTN.setText(_translate("CreateProfileRITADlg", "BLASTN ratio"))
        self.chkNB_BLASTX.setText(_translate("CreateProfileRITADlg", "NB and BLASTX"))
        self.chkBLASTX.setText(_translate("CreateProfileRITADlg", "BLASTX ratio"))
        self.chkNB.setText(_translate("CreateProfileRITADlg", "NB ratio"))
        self.btnCreateProfile.setText(_translate("CreateProfileRITADlg", "Create STAMP profile"))
        self.btnCancel.setText(_translate("CreateProfileRITADlg", "Cancel"))
        self.lstSelectedProfiles.setSortingEnabled(True)
