# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/createProfileBiom.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProfileBiomDlg(object):
    def setupUi(self, CreateProfileBiomDlg):
        CreateProfileBiomDlg.setObjectName("CreateProfileBiomDlg")
        CreateProfileBiomDlg.resize(396, 122)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stamp/GUI/../icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateProfileBiomDlg.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CreateProfileBiomDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblTaxonomyFile = QtWidgets.QLabel(CreateProfileBiomDlg)
        self.lblTaxonomyFile.setObjectName("lblTaxonomyFile")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblTaxonomyFile)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtBiomFile = QtWidgets.QLineEdit(CreateProfileBiomDlg)
        self.txtBiomFile.setObjectName("txtBiomFile")
        self.horizontalLayout.addWidget(self.txtBiomFile)
        self.btnBiomFile = QtWidgets.QPushButton(CreateProfileBiomDlg)
        self.btnBiomFile.setObjectName("btnBiomFile")
        self.horizontalLayout.addWidget(self.btnBiomFile)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(CreateProfileBiomDlg)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cboMetadataField = QtWidgets.QComboBox(CreateProfileBiomDlg)
        self.cboMetadataField.setEditable(True)
        self.cboMetadataField.setObjectName("cboMetadataField")
        self.cboMetadataField.addItem("")
        self.cboMetadataField.addItem("")
        self.cboMetadataField.addItem("")
        self.cboMetadataField.addItem("")
        self.horizontalLayout_2.addWidget(self.cboMetadataField)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnCreateProfile = QtWidgets.QPushButton(CreateProfileBiomDlg)
        self.btnCreateProfile.setObjectName("btnCreateProfile")
        self.horizontalLayout_4.addWidget(self.btnCreateProfile)
        self.btnCancel = QtWidgets.QPushButton(CreateProfileBiomDlg)
        self.btnCancel.setDefault(True)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_4.addWidget(self.btnCancel)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.formLayout)

        self.retranslateUi(CreateProfileBiomDlg)
        QtCore.QMetaObject.connectSlotsByName(CreateProfileBiomDlg)

    def retranslateUi(self, CreateProfileBiomDlg):
        _translate = QtCore.QCoreApplication.translate
        CreateProfileBiomDlg.setWindowTitle(_translate("CreateProfileBiomDlg", "Create profile"))
        self.lblTaxonomyFile.setText(_translate("CreateProfileBiomDlg", "BIOM file:"))
        self.btnBiomFile.setText(_translate("CreateProfileBiomDlg", "Load"))
        self.label_2.setText(_translate("CreateProfileBiomDlg", "Metadata field:"))
        self.cboMetadataField.setItemText(0, _translate("CreateProfileBiomDlg", "<observation ids>"))
        self.cboMetadataField.setItemText(1, _translate("CreateProfileBiomDlg", "COG_Category (PICRUSt COG analysis)"))
        self.cboMetadataField.setItemText(2, _translate("CreateProfileBiomDlg", "KEGG_Pathways (PICRUSt KEGG analysis)"))
        self.cboMetadataField.setItemText(3, _translate("CreateProfileBiomDlg", "taxonomy (QIIME OTU table)"))
        self.btnCreateProfile.setText(_translate("CreateProfileBiomDlg", "Create STAMP profile"))
        self.btnCancel.setText(_translate("CreateProfileBiomDlg", "Cancel"))
