# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/createProfileCoMet.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProfileCoMetDlg(object):
    def setupUi(self, CreateProfileCoMetDlg):
        CreateProfileCoMetDlg.setObjectName("CreateProfileCoMetDlg")
        CreateProfileCoMetDlg.resize(554, 295)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stamp/GUI/../icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateProfileCoMetDlg.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CreateProfileCoMetDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnLoadProfiles = QtWidgets.QPushButton(CreateProfileCoMetDlg)
        self.btnLoadProfiles.setObjectName("btnLoadProfiles")
        self.verticalLayout.addWidget(self.btnLoadProfiles)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnCreateProfile = QtWidgets.QPushButton(CreateProfileCoMetDlg)
        self.btnCreateProfile.setEnabled(False)
        self.btnCreateProfile.setObjectName("btnCreateProfile")
        self.verticalLayout.addWidget(self.btnCreateProfile)
        self.btnCancel = QtWidgets.QPushButton(CreateProfileCoMetDlg)
        self.btnCancel.setObjectName("btnCancel")
        self.verticalLayout.addWidget(self.btnCancel)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.lstSelectedProfiles = QtWidgets.QListWidget(CreateProfileCoMetDlg)
        self.lstSelectedProfiles.setObjectName("lstSelectedProfiles")
        self.horizontalLayout_3.addWidget(self.lstSelectedProfiles)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(CreateProfileCoMetDlg)
        QtCore.QMetaObject.connectSlotsByName(CreateProfileCoMetDlg)

    def retranslateUi(self, CreateProfileCoMetDlg):
        _translate = QtCore.QCoreApplication.translate
        CreateProfileCoMetDlg.setWindowTitle(_translate("CreateProfileCoMetDlg", "Create profile"))
        self.btnLoadProfiles.setText(_translate("CreateProfileCoMetDlg", "Load profiles"))
        self.btnCreateProfile.setText(_translate("CreateProfileCoMetDlg", "Create STAMP profile"))
        self.btnCancel.setText(_translate("CreateProfileCoMetDlg", "Cancel"))
        self.lstSelectedProfiles.setSortingEnabled(True)
