# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/createProfileMgRast.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProfileMgRastDlg(object):
    def setupUi(self, CreateProfileMgRastDlg):
        CreateProfileMgRastDlg.setObjectName("CreateProfileMgRastDlg")
        CreateProfileMgRastDlg.resize(203, 128)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/createProfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateProfileMgRastDlg.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateProfileMgRastDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnLoadProfiles = QtWidgets.QPushButton(CreateProfileMgRastDlg)
        self.btnLoadProfiles.setObjectName("btnLoadProfiles")
        self.verticalLayout.addWidget(self.btnLoadProfiles)
        self.btnCustomizeHeadings = QtWidgets.QPushButton(CreateProfileMgRastDlg)
        self.btnCustomizeHeadings.setEnabled(False)
        self.btnCustomizeHeadings.setObjectName("btnCustomizeHeadings")
        self.verticalLayout.addWidget(self.btnCustomizeHeadings)
        self.btnCreateProfile = QtWidgets.QPushButton(CreateProfileMgRastDlg)
        self.btnCreateProfile.setEnabled(False)
        self.btnCreateProfile.setObjectName("btnCreateProfile")
        self.verticalLayout.addWidget(self.btnCreateProfile)
        self.btnCancel = QtWidgets.QPushButton(CreateProfileMgRastDlg)
        self.btnCancel.setObjectName("btnCancel")
        self.verticalLayout.addWidget(self.btnCancel)

        self.retranslateUi(CreateProfileMgRastDlg)
        QtCore.QMetaObject.connectSlotsByName(CreateProfileMgRastDlg)

    def retranslateUi(self, CreateProfileMgRastDlg):
        _translate = QtCore.QCoreApplication.translate
        CreateProfileMgRastDlg.setWindowTitle(_translate("CreateProfileMgRastDlg", "Create profile"))
        self.btnLoadProfiles.setText(_translate("CreateProfileMgRastDlg", "Load profile"))
        self.btnCustomizeHeadings.setText(_translate("CreateProfileMgRastDlg", "Customize headings"))
        self.btnCreateProfile.setText(_translate("CreateProfileMgRastDlg", "Create STAMP profile"))
        self.btnCancel.setText(_translate("CreateProfileMgRastDlg", "Cancel"))
from stamp import STAMP_rc
