# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/createProfileMothur.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProfileMothurDlg(object):
    def setupUi(self, CreateProfileMothurDlg):
        CreateProfileMothurDlg.setObjectName("CreateProfileMothurDlg")
        CreateProfileMothurDlg.resize(396, 144)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stamp/GUI/../icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateProfileMothurDlg.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CreateProfileMothurDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblTaxonomyFile = QtWidgets.QLabel(CreateProfileMothurDlg)
        self.lblTaxonomyFile.setObjectName("lblTaxonomyFile")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblTaxonomyFile)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtTaxonomyFile = QtWidgets.QLineEdit(CreateProfileMothurDlg)
        self.txtTaxonomyFile.setObjectName("txtTaxonomyFile")
        self.horizontalLayout.addWidget(self.txtTaxonomyFile)
        self.btnTaxonomyFile = QtWidgets.QPushButton(CreateProfileMothurDlg)
        self.btnTaxonomyFile.setObjectName("btnTaxonomyFile")
        self.horizontalLayout.addWidget(self.btnTaxonomyFile)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(CreateProfileMothurDlg)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtGroupsFile = QtWidgets.QLineEdit(CreateProfileMothurDlg)
        self.txtGroupsFile.setObjectName("txtGroupsFile")
        self.horizontalLayout_2.addWidget(self.txtGroupsFile)
        self.btnGroupsFile = QtWidgets.QPushButton(CreateProfileMothurDlg)
        self.btnGroupsFile.setObjectName("btnGroupsFile")
        self.horizontalLayout_2.addWidget(self.btnGroupsFile)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(CreateProfileMothurDlg)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtNamesFile = QtWidgets.QLineEdit(CreateProfileMothurDlg)
        self.txtNamesFile.setObjectName("txtNamesFile")
        self.horizontalLayout_3.addWidget(self.txtNamesFile)
        self.btnNamesFile = QtWidgets.QPushButton(CreateProfileMothurDlg)
        self.btnNamesFile.setObjectName("btnNamesFile")
        self.horizontalLayout_3.addWidget(self.btnNamesFile)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnCreateProfile = QtWidgets.QPushButton(CreateProfileMothurDlg)
        self.btnCreateProfile.setObjectName("btnCreateProfile")
        self.horizontalLayout_4.addWidget(self.btnCreateProfile)
        self.btnCancel = QtWidgets.QPushButton(CreateProfileMothurDlg)
        self.btnCancel.setDefault(True)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_4.addWidget(self.btnCancel)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.verticalLayout_2.addLayout(self.formLayout)

        self.retranslateUi(CreateProfileMothurDlg)
        QtCore.QMetaObject.connectSlotsByName(CreateProfileMothurDlg)

    def retranslateUi(self, CreateProfileMothurDlg):
        _translate = QtCore.QCoreApplication.translate
        CreateProfileMothurDlg.setWindowTitle(_translate("CreateProfileMothurDlg", "Create profile"))
        self.lblTaxonomyFile.setText(_translate("CreateProfileMothurDlg", "Taxonomy file:"))
        self.btnTaxonomyFile.setText(_translate("CreateProfileMothurDlg", "Load"))
        self.label_2.setText(_translate("CreateProfileMothurDlg", "Groups file:"))
        self.btnGroupsFile.setText(_translate("CreateProfileMothurDlg", "Load"))
        self.label_3.setText(_translate("CreateProfileMothurDlg", "Names file (optional):"))
        self.btnNamesFile.setText(_translate("CreateProfileMothurDlg", "Load"))
        self.btnCreateProfile.setText(_translate("CreateProfileMothurDlg", "Create STAMP profile"))
        self.btnCancel.setText(_translate("CreateProfileMothurDlg", "Cancel"))
