# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/groupLegendDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupLegendDlg(object):
    def setupUi(self, GroupLegendDlg):
        GroupLegendDlg.setObjectName("GroupLegendDlg")
        GroupLegendDlg.resize(94, 91)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GroupLegendDlg.sizePolicy().hasHeightForWidth())
        GroupLegendDlg.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/legend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GroupLegendDlg.setWindowIcon(icon)
        GroupLegendDlg.setFloating(True)
        GroupLegendDlg.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollLegend = QtWidgets.QWidget()
        self.scrollLegend.setGeometry(QtCore.QRect(0, 0, 94, 69))
        self.scrollLegend.setObjectName("scrollLegend")
        self.scrollArea.setWidget(self.scrollLegend)
        self.verticalLayout.addWidget(self.scrollArea)
        GroupLegendDlg.setWidget(self.dockWidgetContents)

        self.retranslateUi(GroupLegendDlg)
        QtCore.QMetaObject.connectSlotsByName(GroupLegendDlg)

    def retranslateUi(self, GroupLegendDlg):
        _translate = QtCore.QCoreApplication.translate
        GroupLegendDlg.setWindowTitle(_translate("GroupLegendDlg", "Group legend"))
from stamp import STAMP_rc
