# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/loadDataDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadDataDlg(object):
    def setupUi(self, loadDataDlg):
        loadDataDlg.setObjectName("loadDataDlg")
        loadDataDlg.resize(404, 103)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        loadDataDlg.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(loadDataDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(loadDataDlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtProfileFile = QtWidgets.QLineEdit(loadDataDlg)
        self.txtProfileFile.setObjectName("txtProfileFile")
        self.horizontalLayout.addWidget(self.txtProfileFile)
        self.tbProfileFile = QtWidgets.QToolButton(loadDataDlg)
        self.tbProfileFile.setText("")
        self.tbProfileFile.setIcon(icon)
        self.tbProfileFile.setObjectName("tbProfileFile")
        self.horizontalLayout.addWidget(self.tbProfileFile)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(loadDataDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtMetadataFile = QtWidgets.QLineEdit(loadDataDlg)
        self.txtMetadataFile.setObjectName("txtMetadataFile")
        self.horizontalLayout_2.addWidget(self.txtMetadataFile)
        self.tbMetadataFile = QtWidgets.QToolButton(loadDataDlg)
        self.tbMetadataFile.setText("")
        self.tbMetadataFile.setIcon(icon)
        self.tbMetadataFile.setObjectName("tbMetadataFile")
        self.horizontalLayout_2.addWidget(self.tbMetadataFile)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(loadDataDlg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(loadDataDlg)
        self.buttonBox.accepted.connect(loadDataDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(loadDataDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(loadDataDlg)

    def retranslateUi(self, loadDataDlg):
        _translate = QtCore.QCoreApplication.translate
        loadDataDlg.setWindowTitle(_translate("loadDataDlg", "Load data"))
        self.label.setText(_translate("loadDataDlg", "Profile file:"))
        self.label_2.setText(_translate("loadDataDlg", "Group metadata file (optional):"))
from stamp import STAMP_rc
