# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metadataTableDlg.ui'
#
# Created: Tue Jun 14 10:46:20 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MetadataTableDlg(object):
    def setupUi(self, MetadataTableDlg):
        MetadataTableDlg.setObjectName(_fromUtf8("MetadataTableDlg"))
        MetadataTableDlg.resize(604, 308)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons:table.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MetadataTableDlg.setWindowIcon(icon)
        MetadataTableDlg.setFloating(True)
        MetadataTableDlg.setFeatures(QtWidgets.QDockWidget.DockWidgetFeature.DockWidgetClosable | QtWidgets.QDockWidget.DockWidgetFeature.DockWidgetMovable | QtWidgets.QDockWidget.DockWidgetFeature.DockWidgetFloatable)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.tbMetadataAddAll = QtWidgets.QToolButton(self.dockWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons:filter_add.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbMetadataAddAll.setIcon(icon1)
        self.tbMetadataAddAll.setIconSize(QtCore.QSize(24, 24))
        self.tbMetadataAddAll.setObjectName(_fromUtf8("tbMetadataAddAll"))
        self.horizontalLayout_12.addWidget(self.tbMetadataAddAll)
        self.tbMetadataRemoveAll = QtWidgets.QToolButton(self.dockWidgetContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons:filter_delete.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbMetadataRemoveAll.setIcon(icon2)
        self.tbMetadataRemoveAll.setIconSize(QtCore.QSize(24, 24))
        self.tbMetadataRemoveAll.setObjectName(_fromUtf8("tbMetadataRemoveAll"))
        self.horizontalLayout_12.addWidget(self.tbMetadataRemoveAll)
        spacerItem = QtWidgets.QSpacerItem(12, 1, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.label_70 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_12.addWidget(self.label_70)
        self.cboMetadataAddRemove = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cboMetadataAddRemove.setObjectName(_fromUtf8("cboMetadataAddRemove"))
        self.cboMetadataAddRemove.addItem(_fromUtf8(""))
        self.cboMetadataAddRemove.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.cboMetadataAddRemove)
        self.label_72 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_12.addWidget(self.label_72)
        self.cboMetadataField = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cboMetadataField.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cboMetadataField.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAlphabetically)
        self.cboMetadataField.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.cboMetadataField.setObjectName(_fromUtf8("cboMetadataField"))
        self.horizontalLayout_12.addWidget(self.cboMetadataField)
        self.cboMetadataRelationship = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cboMetadataRelationship.setObjectName(_fromUtf8("cboMetadataRelationship"))
        self.cboMetadataRelationship.addItem(_fromUtf8(""))
        self.cboMetadataRelationship.addItem(_fromUtf8(""))
        self.cboMetadataRelationship.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.cboMetadataRelationship)
        self.cboMetadataValue = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cboMetadataValue.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cboMetadataValue.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.cboMetadataValue.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.cboMetadataValue.setObjectName(_fromUtf8("cboMetadataValue"))
        self.horizontalLayout_12.addWidget(self.cboMetadataValue)
        self.tbMetadataFilter = QtWidgets.QToolButton(self.dockWidgetContents)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons:filter.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbMetadataFilter.setIcon(icon3)
        self.tbMetadataFilter.setIconSize(QtCore.QSize(24, 24))
        self.tbMetadataFilter.setObjectName(_fromUtf8("tbMetadataFilter"))
        self.horizontalLayout_12.addWidget(self.tbMetadataFilter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.tableMetadata = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableMetadata.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableMetadata.setAlternatingRowColors(True)
        self.tableMetadata.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.tableMetadata.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableMetadata.setShowGrid(True)
        self.tableMetadata.setRowCount(5)
        self.tableMetadata.setColumnCount(5)
        self.tableMetadata.setObjectName(_fromUtf8("tableMetadata"))
        self.tableMetadata.setColumnCount(5)
        self.tableMetadata.setRowCount(5)
        self.tableMetadata.horizontalHeader().setVisible(False)
        self.tableMetadata.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableMetadata)
        MetadataTableDlg.setWidget(self.dockWidgetContents)

        self.retranslateUi(MetadataTableDlg)
        self.cboMetadataRelationship.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MetadataTableDlg)

    def retranslateUi(self, MetadataTableDlg):
        MetadataTableDlg.setWindowTitle(QtWidgets.QApplication.translate("MetadataTableDlg", "Metadata table", None))
        self.tbMetadataAddAll.setToolTip(QtWidgets.QApplication.translate("MetadataTableDlg", "Set all samples as active", None))
        self.tbMetadataAddAll.setStatusTip(QtWidgets.QApplication.translate("MetadataTableDlg", "Set all samples as active", None))
        self.tbMetadataAddAll.setText(QtWidgets.QApplication.translate("MetadataTableDlg", "...", None))
        self.tbMetadataRemoveAll.setToolTip(QtWidgets.QApplication.translate("MetadataTableDlg", "Remove all samples from active set", None))
        self.tbMetadataRemoveAll.setStatusTip(QtWidgets.QApplication.translate("MetadataTableDlg", "Remove all samples from active set", None))
        self.tbMetadataRemoveAll.setText(QtWidgets.QApplication.translate("MetadataTableDlg", "...", None))
        self.label_70.setText(QtWidgets.QApplication.translate("MetadataTableDlg", "Filter:", None))
        self.cboMetadataAddRemove.setItemText(0, QtWidgets.QApplication.translate("MetadataTableDlg", "Add", None))
        self.cboMetadataAddRemove.setItemText(1, QtWidgets.QApplication.translate("MetadataTableDlg", "Remove", None))
        self.label_72.setText(QtWidgets.QApplication.translate("MetadataTableDlg", "all samples where", None))
        self.cboMetadataRelationship.setItemText(0, QtWidgets.QApplication.translate("MetadataTableDlg", "<", None))
        self.cboMetadataRelationship.setItemText(1, QtWidgets.QApplication.translate("MetadataTableDlg", "=", None))
        self.cboMetadataRelationship.setItemText(2, QtWidgets.QApplication.translate("MetadataTableDlg", ">", None))
        self.tbMetadataFilter.setToolTip(QtWidgets.QApplication.translate("MetadataTableDlg", "Apply filtering criteria", None))
        self.tbMetadataFilter.setStatusTip(QtWidgets.QApplication.translate("MetadataTableDlg", "Apply filtering criteria", None))
        self.tbMetadataFilter.setText(QtWidgets.QApplication.translate("MetadataTableDlg", "...", None))
        self.tableMetadata.setSortingEnabled(True)

import stamp.STAMP_rc
