# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/multCompCorrectionInfoDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_multCompCorrectionInfoDlg(object):
    def setupUi(self, multCompCorrectionInfoDlg):
        multCompCorrectionInfoDlg.setObjectName("multCompCorrectionInfoDlg")
        multCompCorrectionInfoDlg.resize(400, 170)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        multCompCorrectionInfoDlg.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(multCompCorrectionInfoDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout = QtWidgets.QFormLayout()
        self.layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.layout.setObjectName("layout")
        self.verticalLayout.addLayout(self.layout)

        self.retranslateUi(multCompCorrectionInfoDlg)
        QtCore.QMetaObject.connectSlotsByName(multCompCorrectionInfoDlg)

    def retranslateUi(self, multCompCorrectionInfoDlg):
        _translate = QtCore.QCoreApplication.translate
        multCompCorrectionInfoDlg.setWindowTitle(_translate("multCompCorrectionInfoDlg", "Additional info"))
from stamp import STAMP_rc
