# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/plotDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotDlg(object):
    def setupUi(self, PlotDlg):
        PlotDlg.setObjectName("PlotDlg")
        PlotDlg.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(PlotDlg.sizePolicy().hasHeightForWidth())
        PlotDlg.setSizePolicy(sizePolicy)
        PlotDlg.setMinimumSize(QtCore.QSize(80, 91))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/legend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PlotDlg.setWindowIcon(icon)
        PlotDlg.setFloating(True)
        PlotDlg.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollLegend = QtWidgets.QWidget()
        self.scrollLegend.setGeometry(QtCore.QRect(0, 0, 600, 378))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollLegend.sizePolicy().hasHeightForWidth())
        self.scrollLegend.setSizePolicy(sizePolicy)
        self.scrollLegend.setObjectName("scrollLegend")
        self.scrollArea.setWidget(self.scrollLegend)
        self.verticalLayout.addWidget(self.scrollArea)
        PlotDlg.setWidget(self.dockWidgetContents)

        self.retranslateUi(PlotDlg)
        QtCore.QMetaObject.connectSlotsByName(PlotDlg)

    def retranslateUi(self, PlotDlg):
        _translate = QtCore.QCoreApplication.translate
        PlotDlg.setWindowTitle(_translate("PlotDlg", "Plot"))
from stamp import STAMP_rc
