# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferencesDlg.ui'
#
# Created: Sat Jul 09 17:56:23 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_preferencesDlg(object):
    def setupUi(self, preferencesDlg):
        preferencesDlg.setObjectName(_fromUtf8("preferencesDlg"))
        preferencesDlg.resize(281, 284)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons:pref.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        preferencesDlg.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(preferencesDlg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtWidgets.QGroupBox(preferencesDlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.spinPseudoCount = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinPseudoCount.setDecimals(2)
        self.spinPseudoCount.setMinimum(0.01)
        self.spinPseudoCount.setMaximum(100.0)
        self.spinPseudoCount.setSingleStep(0.1)
        self.spinPseudoCount.setProperty(_fromUtf8("value"), 0.5)
        self.spinPseudoCount.setObjectName(_fromUtf8("spinPseudoCount"))
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinPseudoCount)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.spinReplicates = QtWidgets.QSpinBox(self.groupBox)
        self.spinReplicates.setMinimum(100)
        self.spinReplicates.setMaximum(10000)
        self.spinReplicates.setSingleStep(100)
        self.spinReplicates.setProperty(_fromUtf8("value"), 1000)
        self.spinReplicates.setObjectName(_fromUtf8("spinReplicates"))
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinReplicates)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(preferencesDlg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkTruncateFeatureNames = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkTruncateFeatureNames.setObjectName(_fromUtf8("chkTruncateFeatureNames"))
        self.horizontalLayout.addWidget(self.chkTruncateFeatureNames)
        self.spinFeatureNameLength = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinFeatureNameLength.setMinimum(1)
        self.spinFeatureNameLength.setMaximum(1000)
        self.spinFeatureNameLength.setProperty(_fromUtf8("value"), 10)
        self.spinFeatureNameLength.setObjectName(_fromUtf8("spinFeatureNameLength"))
        self.horizontalLayout.addWidget(self.spinFeatureNameLength)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.btnAxesColour = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxesColour.sizePolicy().hasHeightForWidth())
        self.btnAxesColour.setSizePolicy(sizePolicy)
        self.btnAxesColour.setMinimumSize(QtCore.QSize(22, 22))
        self.btnAxesColour.setMaximumSize(QtCore.QSize(22, 22))
        self.btnAxesColour.setText(_fromUtf8(""))
        self.btnAxesColour.setAutoDefault(False)
        self.btnAxesColour.setObjectName(_fromUtf8("btnAxesColour"))
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnAxesColour)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.btnAllOtherSamplesColour = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAllOtherSamplesColour.sizePolicy().hasHeightForWidth())
        self.btnAllOtherSamplesColour.setSizePolicy(sizePolicy)
        self.btnAllOtherSamplesColour.setMinimumSize(QtCore.QSize(22, 22))
        self.btnAllOtherSamplesColour.setMaximumSize(QtCore.QSize(22, 22))
        self.btnAllOtherSamplesColour.setText(_fromUtf8(""))
        self.btnAllOtherSamplesColour.setAutoDefault(False)
        self.btnAllOtherSamplesColour.setObjectName(_fromUtf8("btnAllOtherSamplesColour"))
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnAllOtherSamplesColour)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.spinMinPvalue = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinMinPvalue.setMinimum(2)
        self.spinMinPvalue.setMaximum(100)
        self.spinMinPvalue.setProperty(_fromUtf8("value"), 15)
        self.spinMinPvalue.setObjectName(_fromUtf8("spinMinPvalue"))
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinMinPvalue)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(preferencesDlg)
        self.btnOK.setObjectName(_fromUtf8("btnOK"))
        self.horizontalLayout_2.addWidget(self.btnOK)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(preferencesDlg)
        QtCore.QMetaObject.connectSlotsByName(preferencesDlg)

    def retranslateUi(self, preferencesDlg):
        preferencesDlg.setWindowTitle(QtWidgets.QApplication.translate("preferencesDlg", "Preferences", None))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("preferencesDlg", "Statistical tests", None))
        self.label.setText(QtWidgets.QApplication.translate("preferencesDlg", "Pseudocount for unobserved data:", None))
        self.label_4.setText(QtWidgets.QApplication.translate("preferencesDlg", "Bootstrap/permutation test replicates", None))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("preferencesDlg", "Plots", None))
        self.chkTruncateFeatureNames.setText(QtWidgets.QApplication.translate("preferencesDlg", "Truncate feature names to length:", None))
        self.label_3.setText(QtWidgets.QApplication.translate("preferencesDlg", "Axis colour:", None))
        self.label_5.setText(QtWidgets.QApplication.translate("preferencesDlg", "All other samples colour:", None))
        self.label_2.setText(QtWidgets.QApplication.translate("preferencesDlg", "Minimum reported p-value, 10^x, x =", None))
        self.spinMinPvalue.setPrefix(QtWidgets.QApplication.translate("preferencesDlg", "-", None))
        self.btnOK.setText(QtWidgets.QApplication.translate("preferencesDlg", "OK", None))

import stamp.STAMP_rc
