# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferencesDlg.ui'
#
# Created: Sat Jul 09 17:56:23 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_preferencesDlg(object):
    def setupUi(self, preferencesDlg):
        preferencesDlg.setObjectName(_fromUtf8("preferencesDlg"))
        preferencesDlg.resize(281, 284)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/pref.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        preferencesDlg.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(preferencesDlg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(preferencesDlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.spinPseudoCount = QtGui.QDoubleSpinBox(self.groupBox)
        self.spinPseudoCount.setDecimals(2)
        self.spinPseudoCount.setMinimum(0.01)
        self.spinPseudoCount.setMaximum(100.0)
        self.spinPseudoCount.setSingleStep(0.1)
        self.spinPseudoCount.setProperty(_fromUtf8("value"), 0.5)
        self.spinPseudoCount.setObjectName(_fromUtf8("spinPseudoCount"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinPseudoCount)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.spinReplicates = QtGui.QSpinBox(self.groupBox)
        self.spinReplicates.setMinimum(100)
        self.spinReplicates.setMaximum(10000)
        self.spinReplicates.setSingleStep(100)
        self.spinReplicates.setProperty(_fromUtf8("value"), 1000)
        self.spinReplicates.setObjectName(_fromUtf8("spinReplicates"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinReplicates)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(preferencesDlg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkTruncateFeatureNames = QtGui.QCheckBox(self.groupBox_2)
        self.chkTruncateFeatureNames.setObjectName(_fromUtf8("chkTruncateFeatureNames"))
        self.horizontalLayout.addWidget(self.chkTruncateFeatureNames)
        self.spinFeatureNameLength = QtGui.QSpinBox(self.groupBox_2)
        self.spinFeatureNameLength.setMinimum(1)
        self.spinFeatureNameLength.setMaximum(1000)
        self.spinFeatureNameLength.setProperty(_fromUtf8("value"), 10)
        self.spinFeatureNameLength.setObjectName(_fromUtf8("spinFeatureNameLength"))
        self.horizontalLayout.addWidget(self.spinFeatureNameLength)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.btnAxesColour = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAxesColour.sizePolicy().hasHeightForWidth())
        self.btnAxesColour.setSizePolicy(sizePolicy)
        self.btnAxesColour.setMinimumSize(QtCore.QSize(22, 22))
        self.btnAxesColour.setMaximumSize(QtCore.QSize(22, 22))
        self.btnAxesColour.setText(_fromUtf8(""))
        self.btnAxesColour.setAutoDefault(False)
        self.btnAxesColour.setObjectName(_fromUtf8("btnAxesColour"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.btnAxesColour)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.btnAllOtherSamplesColour = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAllOtherSamplesColour.sizePolicy().hasHeightForWidth())
        self.btnAllOtherSamplesColour.setSizePolicy(sizePolicy)
        self.btnAllOtherSamplesColour.setMinimumSize(QtCore.QSize(22, 22))
        self.btnAllOtherSamplesColour.setMaximumSize(QtCore.QSize(22, 22))
        self.btnAllOtherSamplesColour.setText(_fromUtf8(""))
        self.btnAllOtherSamplesColour.setAutoDefault(False)
        self.btnAllOtherSamplesColour.setObjectName(_fromUtf8("btnAllOtherSamplesColour"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.btnAllOtherSamplesColour)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinMinPvalue = QtGui.QSpinBox(self.groupBox_2)
        self.spinMinPvalue.setMinimum(2)
        self.spinMinPvalue.setMaximum(100)
        self.spinMinPvalue.setProperty(_fromUtf8("value"), 15)
        self.spinMinPvalue.setObjectName(_fromUtf8("spinMinPvalue"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinMinPvalue)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnOK = QtGui.QPushButton(preferencesDlg)
        self.btnOK.setObjectName(_fromUtf8("btnOK"))
        self.horizontalLayout_2.addWidget(self.btnOK)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(preferencesDlg)
        QtCore.QMetaObject.connectSlotsByName(preferencesDlg)

    def retranslateUi(self, preferencesDlg):
        preferencesDlg.setWindowTitle(QtGui.QApplication.translate("preferencesDlg", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("preferencesDlg", "Statistical tests", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("preferencesDlg", "Pseudocount for unobserved data:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("preferencesDlg", "Bootstrap/permutation test replicates", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("preferencesDlg", "Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTruncateFeatureNames.setText(QtGui.QApplication.translate("preferencesDlg", "Truncate feature names to length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("preferencesDlg", "Axis colour:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("preferencesDlg", "All other samples colour:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("preferencesDlg", "Minimum reported p-value, 10^x, x =", None, QtGui.QApplication.UnicodeUTF8))
        self.spinMinPvalue.setPrefix(QtGui.QApplication.translate("preferencesDlg", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOK.setText(QtGui.QApplication.translate("preferencesDlg", "OK", None, QtGui.QApplication.UnicodeUTF8))

import stamp.STAMP_rc
