# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/selectFeatures.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectFeatureDlg(object):
    def setupUi(self, SelectFeatureDlg):
        SelectFeatureDlg.setObjectName("SelectFeatureDlg")
        SelectFeatureDlg.resize(781, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectFeatureDlg.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(SelectFeatureDlg)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(SelectFeatureDlg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cboHierarchicalLevel = QtWidgets.QComboBox(SelectFeatureDlg)
        self.cboHierarchicalLevel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cboHierarchicalLevel.setObjectName("cboHierarchicalLevel")
        self.horizontalLayout.addWidget(self.cboHierarchicalLevel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(SelectFeatureDlg)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lstSelectedFeatures = QtWidgets.QListWidget(SelectFeatureDlg)
        self.lstSelectedFeatures.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstSelectedFeatures.setObjectName("lstSelectedFeatures")
        self.verticalLayout_2.addWidget(self.lstSelectedFeatures)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnFilterFeature = QtWidgets.QPushButton(SelectFeatureDlg)
        self.btnFilterFeature.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/rightArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFilterFeature.setIcon(icon1)
        self.btnFilterFeature.setObjectName("btnFilterFeature")
        self.verticalLayout.addWidget(self.btnFilterFeature)
        self.btnAddFeature = QtWidgets.QPushButton(SelectFeatureDlg)
        self.btnAddFeature.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/leftArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddFeature.setIcon(icon2)
        self.btnAddFeature.setObjectName("btnAddFeature")
        self.verticalLayout.addWidget(self.btnAddFeature)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(SelectFeatureDlg)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lstFilteredFeatures = QtWidgets.QListWidget(SelectFeatureDlg)
        self.lstFilteredFeatures.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstFilteredFeatures.setObjectName("lstFilteredFeatures")
        self.verticalLayout_3.addWidget(self.lstFilteredFeatures)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(SelectFeatureDlg)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.txtNumSelectedFeatures = QtWidgets.QLineEdit(SelectFeatureDlg)
        self.txtNumSelectedFeatures.setStyleSheet("background-color: rgb(255, 255, 235);")
        self.txtNumSelectedFeatures.setReadOnly(True)
        self.txtNumSelectedFeatures.setObjectName("txtNumSelectedFeatures")
        self.horizontalLayout_2.addWidget(self.txtNumSelectedFeatures)
        spacerItem3 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelectFeatureDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SelectFeatureDlg)
        self.buttonBox.accepted.connect(SelectFeatureDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(SelectFeatureDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectFeatureDlg)

    def retranslateUi(self, SelectFeatureDlg):
        _translate = QtCore.QCoreApplication.translate
        SelectFeatureDlg.setWindowTitle(_translate("SelectFeatureDlg", "Select features"))
        self.label_3.setText(_translate("SelectFeatureDlg", "Hierarchical level:"))
        self.label.setText(_translate("SelectFeatureDlg", "Selected features:"))
        self.lstSelectedFeatures.setSortingEnabled(True)
        self.label_2.setText(_translate("SelectFeatureDlg", "Filtered features:"))
        self.lstFilteredFeatures.setSortingEnabled(True)
        self.label_4.setText(_translate("SelectFeatureDlg", "Number of selected features:"))
from stamp import STAMP_rc
