# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectFeatures.ui'
#
# Created: Fri Apr 29 12:36:32 2011
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SelectFeatureDlg(object):
    def setupUi(self, SelectFeatureDlg):
        SelectFeatureDlg.setObjectName("SelectFeatureDlg")
        SelectFeatureDlg.resize(781, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectFeatureDlg.setWindowIcon(icon)
        self.verticalLayout_4 = QtGui.QVBoxLayout(SelectFeatureDlg)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(SelectFeatureDlg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cboHierarchicalLevel = QtGui.QComboBox(SelectFeatureDlg)
        self.cboHierarchicalLevel.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cboHierarchicalLevel.setObjectName("cboHierarchicalLevel")
        self.horizontalLayout.addWidget(self.cboHierarchicalLevel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(SelectFeatureDlg)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lstSelectedFeatures = QtGui.QListWidget(SelectFeatureDlg)
        self.lstSelectedFeatures.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lstSelectedFeatures.setObjectName("lstSelectedFeatures")
        self.verticalLayout_2.addWidget(self.lstSelectedFeatures)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnFilterFeature = QtGui.QPushButton(SelectFeatureDlg)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/rightArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFilterFeature.setIcon(icon1)
        self.btnFilterFeature.setObjectName("btnFilterFeature")
        self.verticalLayout.addWidget(self.btnFilterFeature)
        self.btnAddFeature = QtGui.QPushButton(SelectFeatureDlg)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/leftArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddFeature.setIcon(icon2)
        self.btnAddFeature.setObjectName("btnAddFeature")
        self.verticalLayout.addWidget(self.btnAddFeature)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtGui.QLabel(SelectFeatureDlg)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lstFilteredFeatures = QtGui.QListWidget(SelectFeatureDlg)
        self.lstFilteredFeatures.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lstFilteredFeatures.setObjectName("lstFilteredFeatures")
        self.verticalLayout_3.addWidget(self.lstFilteredFeatures)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(SelectFeatureDlg)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.txtNumSelectedFeatures = QtGui.QLineEdit(SelectFeatureDlg)
        self.txtNumSelectedFeatures.setStyleSheet("background-color: rgb(255, 255, 235);")
        self.txtNumSelectedFeatures.setReadOnly(True)
        self.txtNumSelectedFeatures.setObjectName("txtNumSelectedFeatures")
        self.horizontalLayout_2.addWidget(self.txtNumSelectedFeatures)
        spacerItem3 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.buttonBox = QtGui.QDialogButtonBox(SelectFeatureDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SelectFeatureDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), SelectFeatureDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), SelectFeatureDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(SelectFeatureDlg)

    def retranslateUi(self, SelectFeatureDlg):
        SelectFeatureDlg.setWindowTitle(QtGui.QApplication.translate("SelectFeatureDlg", "Select features", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SelectFeatureDlg", "Hierarchical level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SelectFeatureDlg", "Selected features:", None, QtGui.QApplication.UnicodeUTF8))
        self.lstSelectedFeatures.setSortingEnabled(True)
        self.label_2.setText(QtGui.QApplication.translate("SelectFeatureDlg", "Filtered features:", None, QtGui.QApplication.UnicodeUTF8))
        self.lstFilteredFeatures.setSortingEnabled(True)
        self.label_4.setText(QtGui.QApplication.translate("SelectFeatureDlg", "Number of selected features:", None, QtGui.QApplication.UnicodeUTF8))

import stamp.STAMP_rc
