# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectFeatures.ui'
#
# Created: Fri Apr 29 12:36:32 2011
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_SelectFeatureDlg(object):
    def setupUi(self, SelectFeatureDlg):
        SelectFeatureDlg.setObjectName("SelectFeatureDlg")
        SelectFeatureDlg.resize(781, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:programIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        SelectFeatureDlg.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(SelectFeatureDlg)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(SelectFeatureDlg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cboHierarchicalLevel = QtWidgets.QComboBox(SelectFeatureDlg)
        self.cboHierarchicalLevel.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.cboHierarchicalLevel.setObjectName("cboHierarchicalLevel")
        self.horizontalLayout.addWidget(self.cboHierarchicalLevel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(SelectFeatureDlg)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lstSelectedFeatures = QtWidgets.QListWidget(SelectFeatureDlg)
        self.lstSelectedFeatures.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.lstSelectedFeatures.setObjectName("lstSelectedFeatures")
        self.verticalLayout_2.addWidget(self.lstSelectedFeatures)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnFilterFeature = QtWidgets.QPushButton(SelectFeatureDlg)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:rightArrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnFilterFeature.setIcon(icon1)
        self.btnFilterFeature.setObjectName("btnFilterFeature")
        self.verticalLayout.addWidget(self.btnFilterFeature)
        self.btnAddFeature = QtWidgets.QPushButton(SelectFeatureDlg)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons:leftArrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAddFeature.setIcon(icon2)
        self.btnAddFeature.setObjectName("btnAddFeature")
        self.verticalLayout.addWidget(self.btnAddFeature)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(SelectFeatureDlg)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lstFilteredFeatures = QtWidgets.QListWidget(SelectFeatureDlg)
        self.lstFilteredFeatures.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.lstFilteredFeatures.setObjectName("lstFilteredFeatures")
        self.verticalLayout_3.addWidget(self.lstFilteredFeatures)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(SelectFeatureDlg)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.txtNumSelectedFeatures = QtWidgets.QLineEdit(SelectFeatureDlg)
        self.txtNumSelectedFeatures.setStyleSheet("background-color: rgb(255, 255, 235);")
        self.txtNumSelectedFeatures.setReadOnly(True)
        self.txtNumSelectedFeatures.setObjectName("txtNumSelectedFeatures")
        self.horizontalLayout_2.addWidget(self.txtNumSelectedFeatures)
        spacerItem3 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelectFeatureDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SelectFeatureDlg)
        self.buttonBox.accepted.connect(SelectFeatureDlg.accept)
        self.buttonBox.rejected.connect(SelectFeatureDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(SelectFeatureDlg)

    def retranslateUi(self, SelectFeatureDlg):
        SelectFeatureDlg.setWindowTitle(QtWidgets.QApplication.translate("SelectFeatureDlg", "Select features", None))
        self.label_3.setText(QtWidgets.QApplication.translate("SelectFeatureDlg", "Hierarchical level:", None))
        self.label.setText(QtWidgets.QApplication.translate("SelectFeatureDlg", "Selected features:", None))
        self.lstSelectedFeatures.setSortingEnabled(True)
        self.label_2.setText(QtWidgets.QApplication.translate("SelectFeatureDlg", "Filtered features:", None))
        self.lstFilteredFeatures.setSortingEnabled(True)
        self.label_4.setText(QtWidgets.QApplication.translate("SelectFeatureDlg", "Number of selected features:", None))

import stamp.STAMP_rc
