# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/GUI/statsTableDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatsTableDlg(object):
    def setupUi(self, StatsTableDlg):
        StatsTableDlg.setObjectName("StatsTableDlg")
        StatsTableDlg.resize(738, 470)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StatsTableDlg.setWindowIcon(icon)
        StatsTableDlg.setFloating(True)
        StatsTableDlg.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableStatisticalSummary = QtWidgets.QTableView(self.dockWidgetContents)
        self.tableStatisticalSummary.setAlternatingRowColors(True)
        self.tableStatisticalSummary.setShowGrid(True)
        self.tableStatisticalSummary.setSortingEnabled(True)
        self.tableStatisticalSummary.setObjectName("tableStatisticalSummary")
        self.verticalLayout.addWidget(self.tableStatisticalSummary)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkShowActiveFeatures = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.chkShowActiveFeatures.setChecked(False)
        self.chkShowActiveFeatures.setObjectName("chkShowActiveFeatures")
        self.horizontalLayout.addWidget(self.chkShowActiveFeatures)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSave = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout)
        StatsTableDlg.setWidget(self.dockWidgetContents)

        self.retranslateUi(StatsTableDlg)
        QtCore.QMetaObject.connectSlotsByName(StatsTableDlg)

    def retranslateUi(self, StatsTableDlg):
        _translate = QtCore.QCoreApplication.translate
        StatsTableDlg.setWindowTitle(_translate("StatsTableDlg", "Statistical summary"))
        self.chkShowActiveFeatures.setText(_translate("StatsTableDlg", "Show only active features"))
        self.btnSave.setText(_translate("StatsTableDlg", "Save"))
from stamp import STAMP_rc
