# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BarPlot.ui'
#
# Created: Fri Apr 22 14:29:49 2011
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_BarPlotDialog(object):
    def setupUi(self, BarPlotDialog):
        BarPlotDialog.setObjectName("BarPlotDialog")
        BarPlotDialog.resize(364, 264)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BarPlotDialog.sizePolicy().hasHeightForWidth())
        BarPlotDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:programIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        BarPlotDialog.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(BarPlotDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFieldToPlot = QtWidgets.QLabel(BarPlotDialog)
        self.lblFieldToPlot.setObjectName("lblFieldToPlot")
        self.horizontalLayout.addWidget(self.lblFieldToPlot)
        self.cboFieldToPlot = QtWidgets.QComboBox(BarPlotDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFieldToPlot.sizePolicy().hasHeightForWidth())
        self.cboFieldToPlot.setSizePolicy(sizePolicy)
        self.cboFieldToPlot.setObjectName("cboFieldToPlot")
        self.cboFieldToPlot.addItem("")
        self.cboFieldToPlot.addItem("")
        self.horizontalLayout.addWidget(self.cboFieldToPlot)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(BarPlotDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.spinFigColWidth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinFigColWidth.setDecimals(2)
        self.spinFigColWidth.setMinimum(0.01)
        self.spinFigColWidth.setMaximum(10.0)
        self.spinFigColWidth.setSingleStep(0.01)
        self.spinFigColWidth.setProperty("value", 0.5)
        self.spinFigColWidth.setObjectName("spinFigColWidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinFigColWidth)
        self.lblFigureHeight = QtWidgets.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName("lblFigureHeight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFigureHeight)
        self.spinFigHeight = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinFigHeight.setMinimum(0.1)
        self.spinFigHeight.setMaximum(20.0)
        self.spinFigHeight.setSingleStep(0.05)
        self.spinFigHeight.setProperty("value", 6.0)
        self.spinFigHeight.setObjectName("spinFigHeight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinFigHeight)
        self.lblFigureWidth = QtWidgets.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName("lblFigureWidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFigureWidth)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.chkShowAverage = QtWidgets.QCheckBox(BarPlotDialog)
        self.chkShowAverage.setChecked(True)
        self.chkShowAverage.setObjectName("chkShowAverage")
        self.verticalLayout_3.addWidget(self.chkShowAverage)
        self.chkShowPvalue = QtWidgets.QCheckBox(BarPlotDialog)
        self.chkShowPvalue.setObjectName("chkShowPvalue")
        self.verticalLayout_3.addWidget(self.chkShowPvalue)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(BarPlotDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioLegendPosNone = QtWidgets.QRadioButton(self.groupBox)
        self.radioLegendPosNone.setObjectName("radioLegendPosNone")
        self.verticalLayout.addWidget(self.radioLegendPosNone)
        self.radioLegendPosBest = QtWidgets.QRadioButton(self.groupBox)
        self.radioLegendPosBest.setChecked(True)
        self.radioLegendPosBest.setObjectName("radioLegendPosBest")
        self.verticalLayout.addWidget(self.radioLegendPosBest)
        self.radioLegendPosUpperRight = QtWidgets.QRadioButton(self.groupBox)
        self.radioLegendPosUpperRight.setObjectName("radioLegendPosUpperRight")
        self.verticalLayout.addWidget(self.radioLegendPosUpperRight)
        self.radioLegendPosCentreRight = QtWidgets.QRadioButton(self.groupBox)
        self.radioLegendPosCentreRight.setObjectName("radioLegendPosCentreRight")
        self.verticalLayout.addWidget(self.radioLegendPosCentreRight)
        self.radioLegendPosLowerRight = QtWidgets.QRadioButton(self.groupBox)
        self.radioLegendPosLowerRight.setObjectName("radioLegendPosLowerRight")
        self.verticalLayout.addWidget(self.radioLegendPosLowerRight)
        self.radioLegendPosUpperLeft = QtWidgets.QRadioButton(self.groupBox)
        self.radioLegendPosUpperLeft.setObjectName("radioLegendPosUpperLeft")
        self.verticalLayout.addWidget(self.radioLegendPosUpperLeft)
        self.radioLegendPosCentreLeft = QtWidgets.QRadioButton(self.groupBox)
        self.radioLegendPosCentreLeft.setObjectName("radioLegendPosCentreLeft")
        self.verticalLayout.addWidget(self.radioLegendPosCentreLeft)
        self.radioLegendPosLowerLeft = QtWidgets.QRadioButton(self.groupBox)
        self.radioLegendPosLowerLeft.setChecked(False)
        self.radioLegendPosLowerLeft.setObjectName("radioLegendPosLowerLeft")
        self.verticalLayout.addWidget(self.radioLegendPosLowerLeft)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(BarPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)

        self.retranslateUi(BarPlotDialog)
        self.buttonBox.accepted.connect(BarPlotDialog.accept)
        self.buttonBox.rejected.connect(BarPlotDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BarPlotDialog)

    def retranslateUi(self, BarPlotDialog):
        BarPlotDialog.setWindowTitle(QtWidgets.QApplication.translate("BarPlotDialog", "Bar plot", None))
        self.lblFieldToPlot.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Field to plot:", None))
        self.cboFieldToPlot.setItemText(0, QtWidgets.QApplication.translate("BarPlotDialog", "Number of sequences", None))
        self.cboFieldToPlot.setItemText(1, QtWidgets.QApplication.translate("BarPlotDialog", "Proportion of sequences (%)", None))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("BarPlotDialog", "Figure size", None))
        self.lblFigureHeight.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Height:", None))
        self.lblFigureWidth.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Column width:", None))
        self.chkShowAverage.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Show average of each group", None))
        self.chkShowPvalue.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Show p-value", None))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("BarPlotDialog", "Legend position", None))
        self.radioLegendPosNone.setText(QtWidgets.QApplication.translate("BarPlotDialog", "None", None))
        self.radioLegendPosBest.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Best", None))
        self.radioLegendPosUpperRight.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Upper right", None))
        self.radioLegendPosCentreRight.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Centre right", None))
        self.radioLegendPosLowerRight.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Lower right", None))
        self.radioLegendPosUpperLeft.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Upper left", None))
        self.radioLegendPosCentreLeft.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Centre left", None))
        self.radioLegendPosLowerLeft.setText(QtWidgets.QApplication.translate("BarPlotDialog", "Lower left", None))

