# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stamp/plugins/groups/plots/configGUI/BoxPlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BoxPlotDialog(object):
    def setupUi(self, BoxPlotDialog):
        BoxPlotDialog.setObjectName("BoxPlotDialog")
        BoxPlotDialog.resize(282, 204)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BoxPlotDialog.sizePolicy().hasHeightForWidth())
        BoxPlotDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stamp/plugins/groups/plots/configGUI/../../../../../icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BoxPlotDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(BoxPlotDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFieldToPlot = QtWidgets.QLabel(BoxPlotDialog)
        self.lblFieldToPlot.setObjectName("lblFieldToPlot")
        self.horizontalLayout.addWidget(self.lblFieldToPlot)
        self.cboFieldToPlot = QtWidgets.QComboBox(BoxPlotDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFieldToPlot.sizePolicy().hasHeightForWidth())
        self.cboFieldToPlot.setSizePolicy(sizePolicy)
        self.cboFieldToPlot.setObjectName("cboFieldToPlot")
        self.cboFieldToPlot.addItem("")
        self.cboFieldToPlot.addItem("")
        self.horizontalLayout.addWidget(self.cboFieldToPlot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(BoxPlotDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.spinFigWidth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinFigWidth.setDecimals(2)
        self.spinFigWidth.setMinimum(0.1)
        self.spinFigWidth.setMaximum(20.0)
        self.spinFigWidth.setSingleStep(0.05)
        self.spinFigWidth.setProperty("value", 6.0)
        self.spinFigWidth.setObjectName("spinFigWidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinFigWidth)
        self.lblFigureHeight = QtWidgets.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName("lblFigureHeight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblFigureHeight)
        self.spinFigHeight = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinFigHeight.setMinimum(0.1)
        self.spinFigHeight.setMaximum(20.0)
        self.spinFigHeight.setSingleStep(0.05)
        self.spinFigHeight.setProperty("value", 6.0)
        self.spinFigHeight.setObjectName("spinFigHeight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinFigHeight)
        self.lblFigureWidth = QtWidgets.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName("lblFigureWidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblFigureWidth)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.chkShowAverage = QtWidgets.QCheckBox(BoxPlotDialog)
        self.chkShowAverage.setChecked(True)
        self.chkShowAverage.setObjectName("chkShowAverage")
        self.verticalLayout.addWidget(self.chkShowAverage)
        self.chkShowPvalue = QtWidgets.QCheckBox(BoxPlotDialog)
        self.chkShowPvalue.setObjectName("chkShowPvalue")
        self.verticalLayout.addWidget(self.chkShowPvalue)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(BoxPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(BoxPlotDialog)
        self.buttonBox.accepted.connect(BoxPlotDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(BoxPlotDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BoxPlotDialog)

    def retranslateUi(self, BoxPlotDialog):
        _translate = QtCore.QCoreApplication.translate
        BoxPlotDialog.setWindowTitle(_translate("BoxPlotDialog", "Box plot"))
        self.lblFieldToPlot.setText(_translate("BoxPlotDialog", "Field to plot:"))
        self.cboFieldToPlot.setItemText(0, _translate("BoxPlotDialog", "Number of sequences"))
        self.cboFieldToPlot.setItemText(1, _translate("BoxPlotDialog", "Proportion of sequences (%)"))
        self.groupBox_3.setTitle(_translate("BoxPlotDialog", "Figure size"))
        self.lblFigureHeight.setText(_translate("BoxPlotDialog", "Height:"))
        self.lblFigureWidth.setText(_translate("BoxPlotDialog", "Width"))
        self.chkShowAverage.setText(_translate("BoxPlotDialog", "Show average of each group"))
        self.chkShowPvalue.setText(_translate("BoxPlotDialog", "Show p-value"))
