# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pcaPlot.ui'
#
# Created: Fri Nov 30 12:52:23 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PcaPlotDialog(object):
    def setupUi(self, PcaPlotDialog):
        PcaPlotDialog.setObjectName(_fromUtf8("PcaPlotDialog"))
        PcaPlotDialog.resize(334, 450)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PcaPlotDialog.sizePolicy().hasHeightForWidth())
        PcaPlotDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/programIcon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PcaPlotDialog.setWindowIcon(icon)
        self.verticalLayout_4 = QtGui.QVBoxLayout(PcaPlotDialog)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(PcaPlotDialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkFixedPixelsPerUnitDistance = QtGui.QCheckBox(self.groupBox_3)
        self.chkFixedPixelsPerUnitDistance.setChecked(True)
        self.chkFixedPixelsPerUnitDistance.setObjectName(_fromUtf8("chkFixedPixelsPerUnitDistance"))
        self.verticalLayout.addWidget(self.chkFixedPixelsPerUnitDistance)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblFigureWidth = QtGui.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName(_fromUtf8("lblFigureWidth"))
        self.horizontalLayout.addWidget(self.lblFigureWidth)
        self.spinFigWidth = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFigWidth.sizePolicy().hasHeightForWidth())
        self.spinFigWidth.setSizePolicy(sizePolicy)
        self.spinFigWidth.setDecimals(2)
        self.spinFigWidth.setMinimum(0.5)
        self.spinFigWidth.setMaximum(20.0)
        self.spinFigWidth.setSingleStep(0.5)
        self.spinFigWidth.setProperty("value", 7.0)
        self.spinFigWidth.setObjectName(_fromUtf8("spinFigWidth"))
        self.horizontalLayout.addWidget(self.spinFigWidth)
        self.lblFigureHeight = QtGui.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName(_fromUtf8("lblFigureHeight"))
        self.horizontalLayout.addWidget(self.lblFigureHeight)
        self.spinFigHeight = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigHeight.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFigHeight.sizePolicy().hasHeightForWidth())
        self.spinFigHeight.setSizePolicy(sizePolicy)
        self.spinFigHeight.setMinimum(0.5)
        self.spinFigHeight.setMaximum(20.0)
        self.spinFigHeight.setSingleStep(0.05)
        self.spinFigHeight.setProperty("value", 6.0)
        self.spinFigHeight.setObjectName(_fromUtf8("spinFigHeight"))
        self.horizontalLayout.addWidget(self.spinFigHeight)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(PcaPlotDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setEnabled(False)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.chkPC3vsPC2 = QtGui.QCheckBox(self.groupBox)
        self.chkPC3vsPC2.setChecked(True)
        self.chkPC3vsPC2.setObjectName(_fromUtf8("chkPC3vsPC2"))
        self.gridLayout.addWidget(self.chkPC3vsPC2, 0, 1, 1, 1)
        self.chkPC1vsPC3 = QtGui.QCheckBox(self.groupBox)
        self.chkPC1vsPC3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkPC1vsPC3.setChecked(True)
        self.chkPC1vsPC3.setObjectName(_fromUtf8("chkPC1vsPC3"))
        self.gridLayout.addWidget(self.chkPC1vsPC3, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_6 = QtGui.QGroupBox(PcaPlotDialog)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.radioLegendPosNone = QtGui.QRadioButton(self.groupBox_6)
        self.radioLegendPosNone.setObjectName(_fromUtf8("radioLegendPosNone"))
        self.verticalLayout_9.addWidget(self.radioLegendPosNone)
        self.radioLegendPosUpperLeft = QtGui.QRadioButton(self.groupBox_6)
        self.radioLegendPosUpperLeft.setChecked(True)
        self.radioLegendPosUpperLeft.setObjectName(_fromUtf8("radioLegendPosUpperLeft"))
        self.verticalLayout_9.addWidget(self.radioLegendPosUpperLeft)
        self.radioLegendPosUpperCentre = QtGui.QRadioButton(self.groupBox_6)
        self.radioLegendPosUpperCentre.setObjectName(_fromUtf8("radioLegendPosUpperCentre"))
        self.verticalLayout_9.addWidget(self.radioLegendPosUpperCentre)
        self.radioLegendPosUpperRight = QtGui.QRadioButton(self.groupBox_6)
        self.radioLegendPosUpperRight.setObjectName(_fromUtf8("radioLegendPosUpperRight"))
        self.verticalLayout_9.addWidget(self.radioLegendPosUpperRight)
        self.radioLegendPosLowerLeft = QtGui.QRadioButton(self.groupBox_6)
        self.radioLegendPosLowerLeft.setObjectName(_fromUtf8("radioLegendPosLowerLeft"))
        self.verticalLayout_9.addWidget(self.radioLegendPosLowerLeft)
        self.radioLegendPosLowerRight = QtGui.QRadioButton(self.groupBox_6)
        self.radioLegendPosLowerRight.setObjectName(_fromUtf8("radioLegendPosLowerRight"))
        self.verticalLayout_9.addWidget(self.radioLegendPosLowerRight)
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(PcaPlotDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinMarkerSize = QtGui.QSpinBox(PcaPlotDialog)
        self.spinMarkerSize.setMinimum(1)
        self.spinMarkerSize.setMaximum(100)
        self.spinMarkerSize.setProperty("value", 30)
        self.spinMarkerSize.setObjectName(_fromUtf8("spinMarkerSize"))
        self.horizontalLayout_2.addWidget(self.spinMarkerSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.chkUniqueShapes = QtGui.QCheckBox(PcaPlotDialog)
        self.chkUniqueShapes.setChecked(True)
        self.chkUniqueShapes.setObjectName(_fromUtf8("chkUniqueShapes"))
        self.verticalLayout_3.addWidget(self.chkUniqueShapes)
        self.chkRotateLabels = QtGui.QCheckBox(PcaPlotDialog)
        self.chkRotateLabels.setChecked(True)
        self.chkRotateLabels.setObjectName(_fromUtf8("chkRotateLabels"))
        self.verticalLayout_3.addWidget(self.chkRotateLabels)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(PcaPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(PcaPlotDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PcaPlotDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PcaPlotDialog.reject)
        QtCore.QObject.connect(self.chkFixedPixelsPerUnitDistance, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinFigHeight.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(PcaPlotDialog)

    def retranslateUi(self, PcaPlotDialog):
        PcaPlotDialog.setWindowTitle(QtGui.QApplication.translate("PcaPlotDialog", "PCA plot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("PcaPlotDialog", "Figure size", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFixedPixelsPerUnitDistance.setText(QtGui.QApplication.translate("PcaPlotDialog", "Fixed pixels per unit distance (recommended)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureWidth.setText(QtGui.QApplication.translate("PcaPlotDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureHeight.setText(QtGui.QApplication.translate("PcaPlotDialog", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PcaPlotDialog", "Plots to show", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("PcaPlotDialog", "PC1 vs. PC2", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPC3vsPC2.setText(QtGui.QApplication.translate("PcaPlotDialog", "PC3 vs. PC2", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPC1vsPC3.setText(QtGui.QApplication.translate("PcaPlotDialog", "PC1 vs. PC3", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("PcaPlotDialog", "Legend position", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosNone.setText(QtGui.QApplication.translate("PcaPlotDialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosUpperLeft.setText(QtGui.QApplication.translate("PcaPlotDialog", "Upper left", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosUpperCentre.setText(QtGui.QApplication.translate("PcaPlotDialog", "Upper centre", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosUpperRight.setText(QtGui.QApplication.translate("PcaPlotDialog", "Upper right", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosLowerLeft.setText(QtGui.QApplication.translate("PcaPlotDialog", "Lower left", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosLowerRight.setText(QtGui.QApplication.translate("PcaPlotDialog", "Lower right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PcaPlotDialog", "Marker size:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUniqueShapes.setText(QtGui.QApplication.translate("PcaPlotDialog", "Assign unique shapes", None, QtGui.QApplication.UnicodeUTF8))
        self.chkRotateLabels.setText(QtGui.QApplication.translate("PcaPlotDialog", "Rotate PC3 labels", None, QtGui.QApplication.UnicodeUTF8))

