# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BarPlot.ui'
#
# Created: Fri Apr 22 14:30:11 2011
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_BarPlotDialog(object):
    def setupUi(self, BarPlotDialog):
        BarPlotDialog.setObjectName("BarPlotDialog")
        BarPlotDialog.resize(364, 264)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BarPlotDialog.sizePolicy().hasHeightForWidth())
        BarPlotDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BarPlotDialog.setWindowIcon(icon)
        self.verticalLayout_4 = QtGui.QVBoxLayout(BarPlotDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFieldToPlot = QtGui.QLabel(BarPlotDialog)
        self.lblFieldToPlot.setObjectName("lblFieldToPlot")
        self.horizontalLayout.addWidget(self.lblFieldToPlot)
        self.cboFieldToPlot = QtGui.QComboBox(BarPlotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFieldToPlot.sizePolicy().hasHeightForWidth())
        self.cboFieldToPlot.setSizePolicy(sizePolicy)
        self.cboFieldToPlot.setObjectName("cboFieldToPlot")
        self.cboFieldToPlot.addItem("")
        self.cboFieldToPlot.addItem("")
        self.horizontalLayout.addWidget(self.cboFieldToPlot)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtGui.QGroupBox(BarPlotDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.spinFigColWidth = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigColWidth.setDecimals(2)
        self.spinFigColWidth.setMinimum(0.01)
        self.spinFigColWidth.setMaximum(10.0)
        self.spinFigColWidth.setSingleStep(0.01)
        self.spinFigColWidth.setProperty("value", 0.5)
        self.spinFigColWidth.setObjectName("spinFigColWidth")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinFigColWidth)
        self.lblFigureHeight = QtGui.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName("lblFigureHeight")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFigureHeight)
        self.spinFigHeight = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigHeight.setMinimum(0.1)
        self.spinFigHeight.setMaximum(20.0)
        self.spinFigHeight.setSingleStep(0.05)
        self.spinFigHeight.setProperty("value", 6.0)
        self.spinFigHeight.setObjectName("spinFigHeight")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinFigHeight)
        self.lblFigureWidth = QtGui.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName("lblFigureWidth")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblFigureWidth)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.chkShowAverage = QtGui.QCheckBox(BarPlotDialog)
        self.chkShowAverage.setChecked(True)
        self.chkShowAverage.setObjectName("chkShowAverage")
        self.verticalLayout_3.addWidget(self.chkShowAverage)
        self.chkShowPvalue = QtGui.QCheckBox(BarPlotDialog)
        self.chkShowPvalue.setObjectName("chkShowPvalue")
        self.verticalLayout_3.addWidget(self.chkShowPvalue)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(BarPlotDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioLegendPosNone = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosNone.setObjectName("radioLegendPosNone")
        self.verticalLayout.addWidget(self.radioLegendPosNone)
        self.radioLegendPosBest = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosBest.setChecked(True)
        self.radioLegendPosBest.setObjectName("radioLegendPosBest")
        self.verticalLayout.addWidget(self.radioLegendPosBest)
        self.radioLegendPosUpperRight = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosUpperRight.setObjectName("radioLegendPosUpperRight")
        self.verticalLayout.addWidget(self.radioLegendPosUpperRight)
        self.radioLegendPosCentreRight = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosCentreRight.setObjectName("radioLegendPosCentreRight")
        self.verticalLayout.addWidget(self.radioLegendPosCentreRight)
        self.radioLegendPosLowerRight = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosLowerRight.setObjectName("radioLegendPosLowerRight")
        self.verticalLayout.addWidget(self.radioLegendPosLowerRight)
        self.radioLegendPosUpperLeft = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosUpperLeft.setObjectName("radioLegendPosUpperLeft")
        self.verticalLayout.addWidget(self.radioLegendPosUpperLeft)
        self.radioLegendPosCentreLeft = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosCentreLeft.setObjectName("radioLegendPosCentreLeft")
        self.verticalLayout.addWidget(self.radioLegendPosCentreLeft)
        self.radioLegendPosLowerLeft = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosLowerLeft.setChecked(False)
        self.radioLegendPosLowerLeft.setObjectName("radioLegendPosLowerLeft")
        self.verticalLayout.addWidget(self.radioLegendPosLowerLeft)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(BarPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)

        self.retranslateUi(BarPlotDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), BarPlotDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), BarPlotDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BarPlotDialog)

    def retranslateUi(self, BarPlotDialog):
        BarPlotDialog.setWindowTitle(QtGui.QApplication.translate("BarPlotDialog", "Bar plot", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFieldToPlot.setText(QtGui.QApplication.translate("BarPlotDialog", "Field to plot:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboFieldToPlot.setItemText(0, QtGui.QApplication.translate("BarPlotDialog", "Number of sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.cboFieldToPlot.setItemText(1, QtGui.QApplication.translate("BarPlotDialog", "Proportion of sequences (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("BarPlotDialog", "Figure size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureHeight.setText(QtGui.QApplication.translate("BarPlotDialog", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureWidth.setText(QtGui.QApplication.translate("BarPlotDialog", "Column width:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowAverage.setText(QtGui.QApplication.translate("BarPlotDialog", "Show average of each group", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowPvalue.setText(QtGui.QApplication.translate("BarPlotDialog", "Show p-value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BarPlotDialog", "Legend position", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosNone.setText(QtGui.QApplication.translate("BarPlotDialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosBest.setText(QtGui.QApplication.translate("BarPlotDialog", "Best", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosUpperRight.setText(QtGui.QApplication.translate("BarPlotDialog", "Upper right", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosCentreRight.setText(QtGui.QApplication.translate("BarPlotDialog", "Centre right", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosLowerRight.setText(QtGui.QApplication.translate("BarPlotDialog", "Lower right", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosUpperLeft.setText(QtGui.QApplication.translate("BarPlotDialog", "Upper left", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosCentreLeft.setText(QtGui.QApplication.translate("BarPlotDialog", "Centre left", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosLowerLeft.setText(QtGui.QApplication.translate("BarPlotDialog", "Lower left", None, QtGui.QApplication.UnicodeUTF8))

