# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BoxPlot.ui'
#
# Created: Fri Apr 22 14:30:09 2011
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_BoxPlotDialog(object):
    def setupUi(self, BoxPlotDialog):
        BoxPlotDialog.setObjectName("BoxPlotDialog")
        BoxPlotDialog.resize(282, 204)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BoxPlotDialog.sizePolicy().hasHeightForWidth())
        BoxPlotDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:programIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        BoxPlotDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(BoxPlotDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFieldToPlot = QtWidgets.QLabel(BoxPlotDialog)
        self.lblFieldToPlot.setObjectName("lblFieldToPlot")
        self.horizontalLayout.addWidget(self.lblFieldToPlot)
        self.cboFieldToPlot = QtWidgets.QComboBox(BoxPlotDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFieldToPlot.sizePolicy().hasHeightForWidth())
        self.cboFieldToPlot.setSizePolicy(sizePolicy)
        self.cboFieldToPlot.setObjectName("cboFieldToPlot")
        self.cboFieldToPlot.addItem("")
        self.cboFieldToPlot.addItem("")
        self.horizontalLayout.addWidget(self.cboFieldToPlot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(BoxPlotDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.spinFigWidth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinFigWidth.setDecimals(2)
        self.spinFigWidth.setMinimum(0.1)
        self.spinFigWidth.setMaximum(20.0)
        self.spinFigWidth.setSingleStep(0.05)
        self.spinFigWidth.setProperty("value", 6.0)
        self.spinFigWidth.setObjectName("spinFigWidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinFigWidth)
        self.lblFigureHeight = QtWidgets.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName("lblFigureHeight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFigureHeight)
        self.spinFigHeight = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinFigHeight.setMinimum(0.1)
        self.spinFigHeight.setMaximum(20.0)
        self.spinFigHeight.setSingleStep(0.05)
        self.spinFigHeight.setProperty("value", 6.0)
        self.spinFigHeight.setObjectName("spinFigHeight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinFigHeight)
        self.lblFigureWidth = QtWidgets.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName("lblFigureWidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFigureWidth)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.chkShowAverage = QtWidgets.QCheckBox(BoxPlotDialog)
        self.chkShowAverage.setChecked(True)
        self.chkShowAverage.setObjectName("chkShowAverage")
        self.verticalLayout.addWidget(self.chkShowAverage)
        self.chkShowPvalue = QtWidgets.QCheckBox(BoxPlotDialog)
        self.chkShowPvalue.setObjectName("chkShowPvalue")
        self.verticalLayout.addWidget(self.chkShowPvalue)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(BoxPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(BoxPlotDialog)
        self.buttonBox.accepted.connect(BoxPlotDialog.accept)
        self.buttonBox.rejected.connect(BoxPlotDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BoxPlotDialog)

    def retranslateUi(self, BoxPlotDialog):
        BoxPlotDialog.setWindowTitle(QtWidgets.QApplication.translate("BoxPlotDialog", "Box plot", None))
        self.lblFieldToPlot.setText(QtWidgets.QApplication.translate("BoxPlotDialog", "Field to plot:", None))
        self.cboFieldToPlot.setItemText(0, QtWidgets.QApplication.translate("BoxPlotDialog", "Number of sequences", None))
        self.cboFieldToPlot.setItemText(1, QtWidgets.QApplication.translate("BoxPlotDialog", "Proportion of sequences (%)", None))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("BoxPlotDialog", "Figure size", None))
        self.lblFigureHeight.setText(QtWidgets.QApplication.translate("BoxPlotDialog", "Height:", None))
        self.lblFigureWidth.setText(QtWidgets.QApplication.translate("BoxPlotDialog", "Width", None))
        self.chkShowAverage.setText(QtWidgets.QApplication.translate("BoxPlotDialog", "Show average of each group", None))
        self.chkShowPvalue.setText(QtWidgets.QApplication.translate("BoxPlotDialog", "Show p-value", None))

