# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PostHocPlot.ui'
#
# Created: Tue May 03 16:52:32 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PostHocPlotDialog(object):
    def setupUi(self, PostHocPlotDialog):
        PostHocPlotDialog.setObjectName(_fromUtf8("PostHocPlotDialog"))
        PostHocPlotDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        PostHocPlotDialog.resize(383, 274)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PostHocPlotDialog.sizePolicy().hasHeightForWidth())
        PostHocPlotDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons:programIcon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PostHocPlotDialog.setWindowIcon(icon)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(PostHocPlotDialog)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_2 = QtWidgets.QGroupBox(PostHocPlotDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cboSortingField = QtWidgets.QComboBox(self.groupBox_2)
        self.cboSortingField.setObjectName(_fromUtf8("cboSortingField"))
        self.cboSortingField.addItem(_fromUtf8(""))
        self.cboSortingField.addItem(_fromUtf8(""))
        self.cboSortingField.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cboSortingField)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(PostHocPlotDialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblFigureWidth = QtWidgets.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName(_fromUtf8("lblFigureWidth"))
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFigureWidth)
        self.spinFigWidth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinFigWidth.setDecimals(2)
        self.spinFigWidth.setMinimum(2.0)
        self.spinFigWidth.setMaximum(20.0)
        self.spinFigWidth.setSingleStep(0.5)
        self.spinFigWidth.setProperty(_fromUtf8("value"), 8.5)
        self.spinFigWidth.setObjectName(_fromUtf8("spinFigWidth"))
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinFigWidth)
        self.lblFigureHeight = QtWidgets.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName(_fromUtf8("lblFigureHeight"))
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFigureHeight)
        self.spinFigRowHeight = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinFigRowHeight.setMinimum(0.1)
        self.spinFigRowHeight.setMaximum(1.0)
        self.spinFigRowHeight.setSingleStep(0.05)
        self.spinFigRowHeight.setProperty(_fromUtf8("value"), 0.25)
        self.spinFigRowHeight.setObjectName(_fromUtf8("spinFigRowHeight"))
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinFigRowHeight)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(PostHocPlotDialog)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.chkCustomLimits = QtWidgets.QCheckBox(self.groupBox_5)
        self.chkCustomLimits.setObjectName(_fromUtf8("chkCustomLimits"))
        self.verticalLayout_4.addWidget(self.chkCustomLimits)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinMinimumX = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinMinimumX.setEnabled(False)
        self.spinMinimumX.setMinimum(-1000.0)
        self.spinMinimumX.setMaximum(1000.0)
        self.spinMinimumX.setSingleStep(0.1)
        self.spinMinimumX.setProperty(_fromUtf8("value"), -1.0)
        self.spinMinimumX.setObjectName(_fromUtf8("spinMinimumX"))
        self.horizontalLayout_4.addWidget(self.spinMinimumX)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinMaximumX = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinMaximumX.setEnabled(False)
        self.spinMaximumX.setMinimum(-1000.0)
        self.spinMaximumX.setMaximum(10000.0)
        self.spinMaximumX.setSingleStep(0.1)
        self.spinMaximumX.setProperty(_fromUtf8("value"), 1.0)
        self.spinMaximumX.setObjectName(_fromUtf8("spinMaximumX"))
        self.horizontalLayout_2.addWidget(self.spinMaximumX)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox = QtWidgets.QGroupBox(PostHocPlotDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkShowBarPlot = QtWidgets.QCheckBox(self.groupBox)
        self.chkShowBarPlot.setChecked(True)
        self.chkShowBarPlot.setObjectName(_fromUtf8("chkShowBarPlot"))
        self.verticalLayout.addWidget(self.chkShowBarPlot)
        self.chkShowStdDev = QtWidgets.QCheckBox(self.groupBox)
        self.chkShowStdDev.setChecked(True)
        self.chkShowStdDev.setObjectName(_fromUtf8("chkShowStdDev"))
        self.verticalLayout.addWidget(self.chkShowStdDev)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinEndCapSize = QtWidgets.QSpinBox(self.groupBox)
        self.spinEndCapSize.setMaximum(100)
        self.spinEndCapSize.setObjectName(_fromUtf8("spinEndCapSize"))
        self.horizontalLayout_5.addWidget(self.spinEndCapSize)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.chkPValueLabels = QtWidgets.QCheckBox(self.groupBox)
        self.chkPValueLabels.setChecked(True)
        self.chkPValueLabels.setObjectName(_fromUtf8("chkPValueLabels"))
        self.verticalLayout.addWidget(self.chkPValueLabels)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinMarkerSize = QtWidgets.QSpinBox(self.groupBox)
        self.spinMarkerSize.setMinimum(1)
        self.spinMarkerSize.setMaximum(100)
        self.spinMarkerSize.setProperty(_fromUtf8("value"), 30)
        self.spinMarkerSize.setObjectName(_fromUtf8("spinMarkerSize"))
        self.horizontalLayout_6.addWidget(self.spinMarkerSize)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.groupBox_4 = QtWidgets.QGroupBox(PostHocPlotDialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.chkFilterPvalue = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkFilterPvalue.setChecked(True)
        self.chkFilterPvalue.setObjectName(_fromUtf8("chkFilterPvalue"))
        self.horizontalLayout_7.addWidget(self.chkFilterPvalue)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(PostHocPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)

        self.retranslateUi(PostHocPlotDialog)
        self.buttonBox.accepted.connect(PostHocPlotDialog.accept)
        self.buttonBox.rejected.connect(PostHocPlotDialog.reject)
        self.chkCustomLimits.clicked.connect(self.spinMinimumX.setEnabled)
        self.chkCustomLimits.clicked.connect(self.spinMaximumX.setEnabled)
        self.chkShowStdDev.clicked.connect(self.spinEndCapSize.setEnabled)
        self.chkShowBarPlot.clicked.connect(self.chkShowStdDev.setEnabled)
        self.chkShowBarPlot.clicked.connect(self.spinEndCapSize.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(PostHocPlotDialog)

    def retranslateUi(self, PostHocPlotDialog):
        PostHocPlotDialog.setWindowTitle(QtWidgets.QApplication.translate("PostHocPlotDialog", "Post-hoc plot", None))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("PostHocPlotDialog", "Sorting", None))
        self.label.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Field:", None))
        self.cboSortingField.setItemText(0, QtWidgets.QApplication.translate("PostHocPlotDialog", "p-values", None))
        self.cboSortingField.setItemText(1, QtWidgets.QApplication.translate("PostHocPlotDialog", "Effect sizes", None))
        self.cboSortingField.setItemText(2, QtWidgets.QApplication.translate("PostHocPlotDialog", "Group labels", None))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("PostHocPlotDialog", "Figure size", None))
        self.lblFigureWidth.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Width:", None))
        self.lblFigureHeight.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Row height:", None))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("PostHocPlotDialog", "Error bar x-axis limits", None))
        self.chkCustomLimits.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Use custom limits", None))
        self.label_2.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Minimum:", None))
        self.label_3.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Maximum:", None))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("PostHocPlotDialog", "Figure elements", None))
        self.chkShowBarPlot.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Show bar subplot", None))
        self.chkShowStdDev.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Show std. dev. on bar subplot", None))
        self.label_5.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "End cap size:", None))
        self.chkPValueLabels.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Show p-value labels", None))
        self.label_4.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Marker size:", None))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("PostHocPlotDialog", "Filter", None))
        self.chkFilterPvalue.setText(QtWidgets.QApplication.translate("PostHocPlotDialog", "Filter rows above norminal level", None))

