# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PostHocPlot.ui'
#
# Created: Tue May 03 16:52:32 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PostHocPlotDialog(object):
    def setupUi(self, PostHocPlotDialog):
        PostHocPlotDialog.setObjectName(_fromUtf8("PostHocPlotDialog"))
        PostHocPlotDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PostHocPlotDialog.resize(383, 274)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PostHocPlotDialog.sizePolicy().hasHeightForWidth())
        PostHocPlotDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/programIcon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PostHocPlotDialog.setWindowIcon(icon)
        self.horizontalLayout_8 = QtGui.QHBoxLayout(PostHocPlotDialog)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_2 = QtGui.QGroupBox(PostHocPlotDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cboSortingField = QtGui.QComboBox(self.groupBox_2)
        self.cboSortingField.setObjectName(_fromUtf8("cboSortingField"))
        self.cboSortingField.addItem(_fromUtf8(""))
        self.cboSortingField.addItem(_fromUtf8(""))
        self.cboSortingField.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cboSortingField)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(PostHocPlotDialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblFigureWidth = QtGui.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName(_fromUtf8("lblFigureWidth"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblFigureWidth)
        self.spinFigWidth = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigWidth.setDecimals(2)
        self.spinFigWidth.setMinimum(2.0)
        self.spinFigWidth.setMaximum(20.0)
        self.spinFigWidth.setSingleStep(0.5)
        self.spinFigWidth.setProperty(_fromUtf8("value"), 8.5)
        self.spinFigWidth.setObjectName(_fromUtf8("spinFigWidth"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinFigWidth)
        self.lblFigureHeight = QtGui.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName(_fromUtf8("lblFigureHeight"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFigureHeight)
        self.spinFigRowHeight = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigRowHeight.setMinimum(0.1)
        self.spinFigRowHeight.setMaximum(1.0)
        self.spinFigRowHeight.setSingleStep(0.05)
        self.spinFigRowHeight.setProperty(_fromUtf8("value"), 0.25)
        self.spinFigRowHeight.setObjectName(_fromUtf8("spinFigRowHeight"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinFigRowHeight)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(PostHocPlotDialog)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.chkCustomLimits = QtGui.QCheckBox(self.groupBox_5)
        self.chkCustomLimits.setObjectName(_fromUtf8("chkCustomLimits"))
        self.verticalLayout_4.addWidget(self.chkCustomLimits)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinMinimumX = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.spinMinimumX.setEnabled(False)
        self.spinMinimumX.setMinimum(-1000.0)
        self.spinMinimumX.setMaximum(1000.0)
        self.spinMinimumX.setSingleStep(0.1)
        self.spinMinimumX.setProperty(_fromUtf8("value"), -1.0)
        self.spinMinimumX.setObjectName(_fromUtf8("spinMinimumX"))
        self.horizontalLayout_4.addWidget(self.spinMinimumX)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinMaximumX = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.spinMaximumX.setEnabled(False)
        self.spinMaximumX.setMinimum(-1000.0)
        self.spinMaximumX.setMaximum(10000.0)
        self.spinMaximumX.setSingleStep(0.1)
        self.spinMaximumX.setProperty(_fromUtf8("value"), 1.0)
        self.spinMaximumX.setObjectName(_fromUtf8("spinMaximumX"))
        self.horizontalLayout_2.addWidget(self.spinMaximumX)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox = QtGui.QGroupBox(PostHocPlotDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkShowBarPlot = QtGui.QCheckBox(self.groupBox)
        self.chkShowBarPlot.setChecked(True)
        self.chkShowBarPlot.setObjectName(_fromUtf8("chkShowBarPlot"))
        self.verticalLayout.addWidget(self.chkShowBarPlot)
        self.chkShowStdDev = QtGui.QCheckBox(self.groupBox)
        self.chkShowStdDev.setChecked(True)
        self.chkShowStdDev.setObjectName(_fromUtf8("chkShowStdDev"))
        self.verticalLayout.addWidget(self.chkShowStdDev)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinEndCapSize = QtGui.QSpinBox(self.groupBox)
        self.spinEndCapSize.setMaximum(100)
        self.spinEndCapSize.setObjectName(_fromUtf8("spinEndCapSize"))
        self.horizontalLayout_5.addWidget(self.spinEndCapSize)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.chkPValueLabels = QtGui.QCheckBox(self.groupBox)
        self.chkPValueLabels.setChecked(True)
        self.chkPValueLabels.setObjectName(_fromUtf8("chkPValueLabels"))
        self.verticalLayout.addWidget(self.chkPValueLabels)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinMarkerSize = QtGui.QSpinBox(self.groupBox)
        self.spinMarkerSize.setMinimum(1)
        self.spinMarkerSize.setMaximum(100)
        self.spinMarkerSize.setProperty(_fromUtf8("value"), 30)
        self.spinMarkerSize.setObjectName(_fromUtf8("spinMarkerSize"))
        self.horizontalLayout_6.addWidget(self.spinMarkerSize)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.groupBox_4 = QtGui.QGroupBox(PostHocPlotDialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.chkFilterPvalue = QtGui.QCheckBox(self.groupBox_4)
        self.chkFilterPvalue.setChecked(True)
        self.chkFilterPvalue.setObjectName(_fromUtf8("chkFilterPvalue"))
        self.horizontalLayout_7.addWidget(self.chkFilterPvalue)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(5, 5, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(PostHocPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)

        self.retranslateUi(PostHocPlotDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PostHocPlotDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PostHocPlotDialog.reject)
        QtCore.QObject.connect(self.chkCustomLimits, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinMinimumX.setEnabled)
        QtCore.QObject.connect(self.chkCustomLimits, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinMaximumX.setEnabled)
        QtCore.QObject.connect(self.chkShowStdDev, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinEndCapSize.setEnabled)
        QtCore.QObject.connect(self.chkShowBarPlot, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.chkShowStdDev.setEnabled)
        QtCore.QObject.connect(self.chkShowBarPlot, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinEndCapSize.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(PostHocPlotDialog)

    def retranslateUi(self, PostHocPlotDialog):
        PostHocPlotDialog.setWindowTitle(QtGui.QApplication.translate("PostHocPlotDialog", "Post-hoc plot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PostHocPlotDialog", "Sorting", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Field:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSortingField.setItemText(0, QtGui.QApplication.translate("PostHocPlotDialog", "p-values", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSortingField.setItemText(1, QtGui.QApplication.translate("PostHocPlotDialog", "Effect sizes", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSortingField.setItemText(2, QtGui.QApplication.translate("PostHocPlotDialog", "Group labels", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("PostHocPlotDialog", "Figure size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureWidth.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureHeight.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Row height:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("PostHocPlotDialog", "Error bar x-axis limits", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCustomLimits.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Use custom limits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Minimum:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Maximum:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PostHocPlotDialog", "Figure elements", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowBarPlot.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Show bar subplot", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowStdDev.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Show std. dev. on bar subplot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PostHocPlotDialog", "End cap size:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPValueLabels.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Show p-value labels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Marker size:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("PostHocPlotDialog", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFilterPvalue.setText(QtGui.QApplication.translate("PostHocPlotDialog", "Filter rows above norminal level", None, QtGui.QApplication.UnicodeUTF8))

